### ISSUE TITLE
llm-gpt4all seems to be breaking on macOS

### ISSUE THREAD

**Issue by govinda-kamath** [simonw/llm-gpt4all#40]
On installing using 
```
~ pipx install llm
~ llm models                                                                                                                                
OpenAI Chat: gpt-3.5-turbo (aliases: 3.5, chatgpt)
OpenAI Chat: gpt-3.5-turbo-16k (aliases: chatgpt-16k, 3.5-16k)
OpenAI Chat: gpt-4 (aliases: 4, gpt4)
OpenAI Chat: gpt-4-32k (aliases: 4-32k)
OpenAI Chat: gpt-4-1106-preview
OpenAI Chat: gpt-4-0125-preview
OpenAI Chat: gpt-4-turbo-2024-04-09
OpenAI Chat: gpt-4-turbo (aliases: gpt-4-turbo-preview, 4-turbo, 4t)
OpenAI Chat: gpt-4o (aliases: 4o)
OpenAI Chat: gpt-4o-mini (aliases: 4o-mini)
OpenAI Completion: gpt-3.5-turbo-instruct (aliases: 3.5-instruct, chatgpt-instruct)
~ llm install llm-gpt4all
```
Then running `llm models list` breaks with the following error

```
~ llm models list                                                                                                                         
Traceback (most recent call last):
  File "/Users/govinda/.local/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/llm/plugins.py", line 17, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/govinda/anaconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/govinda/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import CancellationError as CancellationError, Embed4All as Embed4All, GPT4All as GPT4All
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 23, in <module>
    from ._pyllmodel import (CancellationError as CancellationError, EmbCancelCallbackType, EmbedResult as EmbedResult,
  File "/Users/govinda/.local/pipx/venvs/llm/lib/python3.9/site-packages/gpt4all/_pyllmodel.py", line 34, in <module>
    if subprocess.run(
  File "/Users/govinda/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sysctl', '-n', 'sysctl.proc_translated']' returned non-zero exit status 1
```

**Comment by vskwirblies** [comment]
I'm (probably) having the same issue. Running
`llm --version`
runs fine before installing the gpt4all plugin. After installing the plugin, it throws the shown error message.

**Comment by AnIrishDuck** [comment]
Yeah, this appears to be an upstream issue with gpt4all, [patch submitted](https://github.com/nomic-ai/gpt4all/pull/2992).

It's a simple enough thing to hack around until they fix, one line to edit into wherever the library exists on your machine. I just grabbed the full path from the backtrace.

**Comment by marcintustin** [comment]
Same issue
```
C02CK1UMLVDL:peeprBackend marcintustin$ pipx reinstall llm
uninstalled llm! ✨ 🌟 ✨
  installed package llm 0.19.1, installed using Python 3.13.1
  These apps are now globally available
    - llm
done! ✨ 🌟 ✨
C02CK1UMLVDL:peeprBackend marcintustin$ llm models
OpenAI Chat: gpt-4o (aliases: 4o)
OpenAI Chat: gpt-4o-mini (aliases: 4o-mini)
OpenAI Chat: gpt-4o-audio-preview
OpenAI Chat: gpt-3.5-turbo (aliases: 3.5, chatgpt)
OpenAI Chat: gpt-3.5-turbo-16k (aliases: chatgpt-16k, 3.5-16k)
OpenAI Chat: gpt-4 (aliases: 4, gpt4)
OpenAI Chat: gpt-4-32k (aliases: 4-32k)
OpenAI Chat: gpt-4-1106-preview
OpenAI Chat: gpt-4-0125-preview
OpenAI Chat: gpt-4-turbo-2024-04-09
OpenAI Chat: gpt-4-turbo (aliases: gpt-4-turbo-preview, 4-turbo, 4t)
OpenAI Chat: o1-preview
OpenAI Chat: o1-mini
OpenAI Completion: gpt-3.5-turbo-instruct (aliases: 3.5-instruct, chatgpt-instruct)
C02CK1UMLVDL:peeprBackend marcintustin$ llm install llm-gpt4all
Collecting llm-gpt4all
  Using cached llm_gpt4all-0.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: llm>=0.11 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm-gpt4all) (0.19.1)
Collecting gpt4all>=2.5.1 (from llm-gpt4all)
  Using cached gpt4all-2.8.2-py3-none-macosx_10_15_universal2.whl.metadata (4.8 kB)
Requirement already satisfied: httpx in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm-gpt4all) (0.28.1)
Collecting requests (from gpt4all>=2.5.1->llm-gpt4all)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: tqdm in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from gpt4all>=2.5.1->llm-gpt4all) (4.67.1)
Requirement already satisfied: click in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (8.1.7)
Requirement already satisfied: openai>=1.0 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (1.57.2)
Requirement already satisfied: click-default-group>=1.2.3 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (1.2.4)
Requirement already satisfied: sqlite-utils>=3.37 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (3.38)
Requirement already satisfied: sqlite-migrate>=0.1a2 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (0.1b0)
Requirement already satisfied: pydantic>=1.10.2 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (2.10.3)
Requirement already satisfied: PyYAML in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (6.0.2)
Requirement already satisfied: pluggy in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (1.5.0)
Requirement already satisfied: python-ulid in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (3.0.0)
Requirement already satisfied: setuptools in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (75.6.0)
Requirement already satisfied: pip in /Users/marcintustin/.local/pipx/shared/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (24.3.1)
Requirement already satisfied: puremagic in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from llm>=0.11->llm-gpt4all) (1.28)
Requirement already satisfied: anyio in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from httpx->llm-gpt4all) (4.7.0)
Requirement already satisfied: certifi in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from httpx->llm-gpt4all) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from httpx->llm-gpt4all) (1.0.7)
Requirement already satisfied: idna in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from httpx->llm-gpt4all) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from httpcore==1.*->httpx->llm-gpt4all) (0.14.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from openai>=1.0->llm>=0.11->llm-gpt4all) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from openai>=1.0->llm>=0.11->llm-gpt4all) (0.8.2)
Requirement already satisfied: sniffio in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from openai>=1.0->llm>=0.11->llm-gpt4all) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from openai>=1.0->llm>=0.11->llm-gpt4all) (4.12.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from pydantic>=1.10.2->llm>=0.11->llm-gpt4all) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from pydantic>=1.10.2->llm>=0.11->llm-gpt4all) (2.27.1)
Requirement already satisfied: sqlite-fts4 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from sqlite-utils>=3.37->llm>=0.11->llm-gpt4all) (1.0.3)
Requirement already satisfied: tabulate in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from sqlite-utils>=3.37->llm>=0.11->llm-gpt4all) (0.9.0)
Requirement already satisfied: python-dateutil in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from sqlite-utils>=3.37->llm>=0.11->llm-gpt4all) (2.9.0.post0)
Collecting charset-normalizer<4,>=2 (from requests->gpt4all>=2.5.1->llm-gpt4all)
  Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests->gpt4all>=2.5.1->llm-gpt4all)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.5 in /Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages (from python-dateutil->sqlite-utils>=3.37->llm>=0.11->llm-gpt4all) (1.17.0)
Using cached llm_gpt4all-0.4-py3-none-any.whl (10 kB)
Using cached gpt4all-2.8.2-py3-none-macosx_10_15_universal2.whl (6.6 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_10_13_x86_64.whl (125 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, charset-normalizer, requests, gpt4all, llm-gpt4all
Successfully installed charset-normalizer-3.4.0 gpt4all-2.8.2 llm-gpt4all-0.4 requests-2.32.3 urllib3-2.2.3
C02CK1UMLVDL:peeprBackend marcintustin$ llm models
Traceback (most recent call last):
  File "/Users/marcintustin/.local/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/llm/cli.py", line 1887, in <module>
    load_plugins()
    ~~~~~~~~~~~~^^
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/llm/plugins.py", line 25, in load_plugins
    pm.load_setuptools_entrypoints("llm")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import CancellationError as CancellationError, Embed4All as Embed4All, GPT4All as GPT4All
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/gpt4all/gpt4all.py", line 23, in <module>
    from ._pyllmodel import (CancellationError as CancellationError, EmbCancelCallbackType, EmbedResult as EmbedResult,
                             LLModel, ResponseCallbackType, empty_response_callback)
  File "/Users/marcintustin/.local/pipx/venvs/llm/lib/python3.13/site-packages/gpt4all/_pyllmodel.py", line 34, in <module>
    if subprocess.run(
       ~~~~~~~~~~~~~~^
        "sysctl -n sysctl.proc_translated".split(), check=True, capture_output=True, text=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).stdout.strip() == "1":
    ^
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sysctl', '-n', 'sysctl.proc_translated']' returned non-zero exit status 1.
C02CK1UMLVDL:peeprBackend marcintustin$ 

```

**Comment by QuantumLibet** [comment]
Until this is fixed and released, use this as a workaround:

After installing the plugin with `llm install llm-gpt4all` delete the offending instruction with `sed -i '' 's/check=True, //' ~/.local/pipx/venvs/llm/lib/python3*/site-packages/gpt4all/_pyllmodel.py`.
